OPENQASM 2.0;
include "qelib1.inc";
qreg qregless[8];
creg cregless[8];
h qregless[0];
s qregless[0];
s qregless[0];
h qregless[0];
h qregless[1];
h qregless[1];
h qregless[2];
s qregless[2];
s qregless[2];
h qregless[2];
h qregless[2];
h qregless[3];
s qregless[3];
s qregless[3];
h qregless[3];
h qregless[4];
s qregless[4];
s qregless[4];
h qregless[4];
h qregless[4];
h qregless[5];
s qregless[5];
s qregless[5];
h qregless[5];
h qregless[5];
h qregless[7];
h qregless[7];
measure qregless[6] -> cregless[0];
h qregless[6];
measure qregless[6] -> cregless[0];
measure qregless[0] -> cregless[1];
h qregless[0];
s qregless[0];
s qregless[0];
h qregless[0];
measure qregless[0] -> cregless[1];
measure qregless[3] -> cregless[2];
h qregless[3];
s qregless[3];
s qregless[3];
h qregless[3];
h qregless[3];
measure qregless[3] -> cregless[2];
measure qregless[1] -> cregless[3];
h qregless[1];
h qregless[1];
measure qregless[1] -> cregless[3];
measure qregless[2] -> cregless[4];
h qregless[2];
s qregless[2];
s qregless[2];
h qregless[2];
h qregless[2];
h qregless[2];
measure qregless[2] -> cregless[4];
measure qregless[4] -> cregless[5];
h qregless[4];
s qregless[4];
s qregless[4];
h qregless[4];
h qregless[4];
h qregless[4];
measure qregless[4] -> cregless[5];
measure qregless[5] -> cregless[6];
h qregless[5];
measure qregless[5] -> cregless[6];
measure qregless[7] -> cregless[7];
h qregless[7];
h qregless[7];
measure qregless[7] -> cregless[7];
