OPENQASM 2.0;
include "qelib1.inc";
qreg qregless[14];
creg cregless[13];
h qregless[0];
h qregless[1];
h qregless[2];
h qregless[3];
h qregless[4];
h qregless[5];
h qregless[6];
h qregless[7];
h qregless[8];
h qregless[9];
h qregless[10];
h qregless[11];
h qregless[12];
h qregless[13];
s qregless[13];
s qregless[13];
h qregless[13];
h qregless[13];
barrier qregless[0],qregless[1],qregless[2],qregless[3],qregless[4],qregless[5],qregless[6],qregless[7],qregless[8],qregless[9],qregless[10],qregless[11],qregless[12],qregless[13];
cx qregless[0],qregless[13];
cx qregless[1],qregless[13];
cx qregless[2],qregless[13];
cx qregless[3],qregless[13];
cx qregless[4],qregless[13];
cx qregless[5],qregless[13];
cx qregless[6],qregless[13];
cx qregless[7],qregless[13];
cx qregless[8],qregless[13];
cx qregless[9],qregless[13];
cx qregless[10],qregless[13];
cx qregless[11],qregless[13];
cx qregless[12],qregless[13];
barrier qregless[0],qregless[1],qregless[2],qregless[3],qregless[4],qregless[5],qregless[6],qregless[7],qregless[8],qregless[9],qregless[10],qregless[11],qregless[12],qregless[13];
h qregless[0];
h qregless[1];
h qregless[10];
h qregless[11];
h qregless[12];
h qregless[2];
h qregless[3];
h qregless[4];
h qregless[5];
h qregless[6];
h qregless[7];
h qregless[8];
h qregless[9];
measure qregless[0] -> cregless[0];
measure qregless[1] -> cregless[1];
measure qregless[2] -> cregless[2];
measure qregless[3] -> cregless[3];
measure qregless[4] -> cregless[4];
measure qregless[5] -> cregless[5];
measure qregless[6] -> cregless[6];
measure qregless[7] -> cregless[7];
measure qregless[8] -> cregless[8];
measure qregless[9] -> cregless[9];
measure qregless[10] -> cregless[10];
measure qregless[11] -> cregless[11];
measure qregless[12] -> cregless[12];
