OPENQASM 2.0;
include "qelib1.inc";
qreg qregless[17];
creg cregless[8];
h qregless[0];
cx qregless[0],qregless[3];
h qregless[3];
cx qregless[3],qregless[4];
cx qregless[3],qregless[5];
cx qregless[0],qregless[6];
h qregless[0];
cx qregless[0],qregless[1];
cx qregless[0],qregless[2];
h qregless[6];
cx qregless[6],qregless[7];
cx qregless[6],qregless[8];
cx qregless[0],qregless[9];
h qregless[0];
cx qregless[1],qregless[9];
cx qregless[1],qregless[10];
h qregless[1];
cx qregless[2],qregless[10];
h qregless[2];
cx qregless[3],qregless[11];
h qregless[3];
cx qregless[4],qregless[11];
cx qregless[4],qregless[12];
h qregless[4];
cx qregless[5],qregless[12];
h qregless[5];
cx qregless[6],qregless[13];
h qregless[6];
cx qregless[7],qregless[13];
cx qregless[7],qregless[14];
h qregless[7];
cx qregless[8],qregless[14];
h qregless[8];
cx qregless[0],qregless[15];
h qregless[0];
cx qregless[1],qregless[15];
h qregless[1];
cx qregless[2],qregless[15];
h qregless[2];
cx qregless[3],qregless[16];
cx qregless[3],qregless[15];
h qregless[3];
cx qregless[4],qregless[16];
cx qregless[4],qregless[15];
h qregless[4];
cx qregless[5],qregless[16];
cx qregless[5],qregless[15];
h qregless[5];
cx qregless[6],qregless[16];
h qregless[6];
cx qregless[7],qregless[16];
h qregless[7];
cx qregless[8],qregless[16];
measure qregless[9] -> cregless[0];
measure qregless[10] -> cregless[1];
measure qregless[11] -> cregless[2];
measure qregless[12] -> cregless[3];
measure qregless[13] -> cregless[4];
measure qregless[14] -> cregless[5];
measure qregless[15] -> cregless[6];
measure qregless[16] -> cregless[7];
