OPENQASM 2.0;
include "qelib1.inc";
qreg qregless[5];
creg cregless[5];
h qregless[0];
s qregless[0];
s qregless[0];
h qregless[0];
barrier qregless[0],qregless[1],qregless[2];
cx qregless[0],qregless[3];
cx qregless[1],qregless[3];
cx qregless[1],qregless[4];
cx qregless[2],qregless[4];
measure qregless[3] -> cregless[3];
measure qregless[4] -> cregless[4];
if(syn==1) h qregless[0];
if(syn==1) s qregless[0];
if(syn==1) s qregless[0];
if(syn==1) h qregless[0];
measure qregless[0] -> cregless[0];
if(syn==2) h qregless[2];
if(syn==2) s qregless[2];
if(syn==2) s qregless[2];
if(syn==2) h qregless[2];
if(syn==3) h qregless[1];
if(syn==3) s qregless[1];
if(syn==3) s qregless[1];
if(syn==3) h qregless[1];
measure qregless[1] -> cregless[1];
measure qregless[2] -> cregless[2];
